# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq texlive
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh
    - sudo sh lilypond-2.18.2-1.linux-64.sh --batch

r_packages:
    - formatR

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/070543d2c2d6a3d016d4
    on_success: change
    on_failure: always
    on_start: never

after_success:
    - Rscript -e 'covr::codecov(function_exclusions = "\\.onLoad$", line_exclusions = list("R/tab.R" = 169))'
